[package]
name = "lmvc8-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
compiler = []
debugger = []
disassembler = []
emulator = []

[dependencies]
binrw = { workspace = true }
thiserror = { workspace = true }